name: release
run-name: "Release ${{github.ref_name}} by @${{github.actor}}"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # allow goreleaser upload archives as GitHub Releases
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0  # fetch all commits, tags and branches
      - name: "Setup Go"
        uses: "actions/setup-go@v5"
        with:
          go-version: "1.22.2"
      - name: "Run GoReleaser"
        uses: "goreleaser/goreleaser-action@v6"
        with:
          distribution: "goreleaser"
          version: "~> v1"  # goreleaser version
          args: "release --clean"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Update new version in krew-index"
        uses: "rajatjindal/krew-release-bot@v0.0.46"
